<?php
/**
 * Created by PhpStorm.
 * User: Allen
 * Date: 2017/11/12
 * Time: 20:27
 */

namespace  app\models;


use yii\base\Model;


class  Test extends  Model {

    private $name;
    private $age;

    public function rules()
    {
        return [
            [['name'],'string','max'=>5],
            [['age'],'integer'],

        ];
//        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function getHobby(){
        return "game";
    }

    public function setName($value){
         $this->name = 'ggg'.$value;
    }
    public function getName(){
        return $this->name;
    }

}