<?php
/**
 * Created by PhpStorm.
 * User: Allen
 * Date: 2017/11/13
 * Time: 23:14
 */

namespace   app\component;

use yii\base\Behavior;

class  MyBehavior extends  Behavior
{
    public function events()
    {
        echo '222<br>';
        return parent::events(); // TODO: Change the autogenerated stub

    }

    public function m()
    {
        echo "m<br>";
    }

}