<?php
/**
 * Created by PhpStorm.
 * User: Allen
 * Date: 2017/11/13
 * Time: 23:19
 */
namespace  app\component;

use yii\base\Behavior;

class MyBehavior1 extends  Behavior
{

    public function events()
    {
        return parent::events(); // TODO: Change the autogenerated stub
    }

    public function m1()
    {
        echo 'm1<br>';
    }

}