<?php
/**
 * Created by PhpStorm.
 * User: Allen
 * Date: 2017/11/13
 * Time: 23:14
 */

namespace   app\component;

use yii\base\Behavior;

class  MyBehavior extends  Behavior
{
    public function events()
    {

       // return parent::events();
        //return parent::events(); // TODO: Change the autogenerated stub

        return [
            \yii\base\Controller::EVENT_AFTER_ACTION => 'm'
        ];

    }

    public function m()
    {
        echo "this m <br>";
        file_put_contents("a.txt",date('Y-m-d H:i:s'));

    }

}